### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by wimglenn** [mgeier/pytest-auto-parametrize#1]
Seems it stopped working at some stage.

```
Traceback (most recent call last):
  File "/home/myuser/git/pytest-auto-parametrize/.venv/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 653, in pytest_cmdline_parse
    self.parse(args)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 825, in parse
    self._preparse(args, addopts=addopts)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 777, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 253, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 290, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/myuser/git/pytest-auto-parametrize/pytest_auto_parametrize.py", line 3, in <module>
    from _pytest.mark import extract_argvalue
ImportError: cannot import name 'extract_argvalue' from '_pytest.mark' (/home/myuser/git/pytest-auto-parametrize/.venv/lib/python3.7/site-packages/_pytest/mark/__init__.py)
```

**Comment by mgeier** [comment]
Thanks for the report!

This seems to have been broken since a few months after I created it. So I guess nobody was using this plugin before you ...

I asked if using `_pytest.mark.extract_argvalue()` is a good idea (https://github.com/pytest-dev/pytest/pull/780#issuecomment-246188716), and apparently it wasn't a good idea because it was removed in https://github.com/pytest-dev/pytest/pull/1921 (more specifically in commit https://github.com/pytest-dev/pytest/commit/e368fb4b29912fe618d523b2ca9197016738d7d6).

I've created #2, but there is still another problem, see #3.
